databases:
  - name: lokesh
    databaseName: lokesh_v40b
    user: lokesh_v40b_user

services:
  - type: web
    name: lokesh
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lokesh
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false